sistem-pakar-dempster-shafer/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PenyakitController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\GejalaController;
use App\Http\Controllers\RuleController;
use App\Http\Controllers\KonsultasiController;
use App\Http\Controllers\HasilController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('home');
// });

Route::get('/dashboard', [DashboardController::class, 'index']);

Route::resource('penyakit', PenyakitController::class);

Route::resource('gejala', GejalaController::class);

Route::resource('rule', RuleController::class);

Route::resource('hasil', HasilController::class);

Route::resource('konsultasi', KonsultasiController::class);

Route::post('/konsultasi', [KonsultasiController::class, 'konsultasi']);

Route::get('/', [KonsultasiController::class, 'toHome']);

Auth::routes();

Route::get('/konsultasi', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

sistem-pakar-dempster-shafer/app/Models/Gejala.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Gejala extends Model
{
    use HasFactory;

    protected $table = "gejala";

    protected $guarded = [];
}

sistem-pakar-dempster-shafer/app/Http/Controllers/GejalaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Gejala;
use RealRashid\SweetAlert\Facades\Alert;

class GejalaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $listgejala = Gejala::paginate(10);

        return view('gejala.index', compact('listgejala'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // Validasi
        $request->validate([
            'kode_gejala' => 'unique:gejala|max:5|min:2',            
            'gejala' => 'required'
        ]);

        $penyakit = Gejala::create([
            'kode_gejala' => $request['kode_gejala'],
            'gejala' => $request['gejala']
        ]);

        Alert::success('Success', 'Gejala Baru Berhasil Ditambahkan!');
           
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $gejala = Gejala::find($id);

        $gejala->kode_gejala = $request['kode_gejala'];
        $gejala->gejala = $request['gejala'];
        $gejala->save();

        Alert::success('Success', 'Data Gejala Berhasil Diperbarui!');
           
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $gejala = Gejala::findorfail($id);
        $gejala->delete();

        Alert::success('Success', 'Gejala Berhasil Dihapus!');

        return redirect()->back();
    }
}

sistem-pakar-dempster-shafer/resources/views/gejala/index.blade.php
@extends('layout.admin')

@section('content-header')
    <h1 class="h3 mb-4 text-gray-800">
        <i class="fa-solid fa-list"></i> Data Gejala
        <button class="btn btn-primary fa-pull-right" data-toggle="modal" data-target="#modal_tambah_gejala"><i class="fa-solid fa-plus"></i> Tambah Data</button>
    </h1>
@endsection

@section('content')
    <!-- DataTales Example -->
    <div class="card shadow mb-4">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Daftar Gejala</h6>
      </div>
      <div class="card-body">
        
        <div class="table-responsive">
          <table class="table table-bordered text-center" id="dataTable" width="100%" cellspacing="0">
            <thead class="bg-primary text-light">
              <tr>
                <th>Kode Gejala</th>
                <th>Gejala</th>
                <th>Aksi</th>
              </tr>
            </thead>
            <tbody>
              @forelse ($listgejala as $item)                                              
                <tr>
                  <td width="10%">{{ $item->kode_gejala }}</td>
                  <td width="80%">{{ $item->gejala }}</td>
                  <td>
                    <button class="btn btn-success btn-sm mr-2" data-toggle="modal" data-target="#modal_edit_gejala{{ $item->id }}">Edit</button>
                    <button class="btn btn-danger btn-sm mr-2" data-toggle="modal" data-target="#modal_hapus_gejala{{ $item->id }}"><i class="fa-solid fa-trash"></i></button>
                  </td>
                </tr>
              @empty
                <tr>
                  <td colspan="3" align="center">Belum ada data</td>    
                </tr>                      
              @endforelse
            </tbody>
          </table>
        </div>
      </div>
    </div>
    {{ $listgejala->links() }}

    {{-- Modal Tambah Gejala --}}
<div class="modal fade" id="modal_tambah_gejala" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"><i class="fa-solid fa-plus"></i> Tambah Data Gejala</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="{{ route('gejala.store') }}" method="POST">
            @csrf
            <div class="form-group">
                <label>Kode Gejala</label>
                <input type="text" class="form-control" id="kode_gejala" name="kode_gejala" maxlength="5" minlength="2" autocomplete="off" required>
            </div>
            <div class="form-group">
                <label>Gejala</label>
                <textarea class="form-control" id="gejala" name="gejala" required></textarea>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Tutup</button>
              <button type="submit" class="btn btn-primary">Simpan</button>
            </div>
        </form>
      </div>
    </div>
  </div>
</div>
{{-- Akhir Modal Tambah Gejala --}}

{{-- Modal Edit Gejala --}}
@foreach ($listgejala as $item)
<div class="modal fade" id="modal_edit_gejala{{ $item->id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"><i class="fa-solid fa-pen-to-square"></i> Edit Data Gejala</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="/gejala/{{$item->id}}" method="POST">
            @csrf
            @method('PUT')
            <div class="form-group">
                <label>Kode Gejala</label>
                <input type="text" class="form-control" id="kode_gejala" name="kode_gejala" maxlength="5" minlength="2" autocomplete="off" value="{{ old('kode_gejala', $item->kode_gejala ) }}" required>
            </div>
            <div class="form-group">
                <label>Gejala</label>
                <textarea class="form-control" id="gejala" name="gejala" required>{{ old('gejala', $item->gejala ) }}</textarea>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Tutup</button>
              <button type="submit" class="btn btn-primary">Simpan</button>
            </div>
        </form>
      </div>
    </div>
  </div>
</div>
@endforeach
{{-- Akhir Modal Edit Gejala --}}

{{-- Modal Hapus gejala --}}
@foreach ($listgejala as $item)
<div class="modal fade" id="modal_hapus_gejala{{$item->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalCenterTitle">Hapus Gejala</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="form-group">
            <h5 class="text-center">Anda yakin ingin menghapus gejala ini?</h5>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">Tutup</button>
            <form action="/gejala/{{$item->id}}" method="POST">
              @csrf
              @method('DELETE')        
              <input type="submit" name="delete" id="delete" value='Hapus' class="btn btn-danger btn-sm">
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
@endforeach
{{-- Akhir Modal Hapus Gejala --}}
@endsection